config/routes.rb
Rails.application.routes.draw do
  #root 'static_pages#home'
  root :to => 'sessions#new'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  get 'users/new'
  get  '/home', to: 'static_pages#home'
  get  '/help', to: 'static_pages#help'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup', to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",  '#' %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-inverse navbar-fixed-top app-navbar">
    <div class="container">
      <div class="navbar-header">
        <button aria-expanded="false" type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-main">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "FATCAMP", root_path, id: "logo", class: 'navbar-brand' %>
      </div>
      <div class="navbar-collapse collapse" id="navbar-collapse-main">
        <ul class="nav navbar-nav hidden-xs">
          <li><%= link_to "Fat Stream", current_user %></li>
          <li><%= link_to "All Fatties", users_path %></li>
          <li><%= link_to "Your Progress", help_path %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right m-r-0 hidden-xs">
          <li>
            <button class="btn btn-default navbar-btn navbar-btn-avitar" data-toggle="popover">
              <img class="img-circle" src="assets/img/adrian.jpg">
            </button>
          </li>
        </ul>
        <ul class="nav navbar-nav hidden-sm hidden-md hidden-lg">
          <li><a href="home.html">Fat Stream</a></li>
          <li><a href="all-users.html">All Fatties</a></li>
          <li><a href="profile.html">Your Progress</a></li>
          <li><a href="edit-profile.html">Edit Profile</a></li>
          <li><a href="login/index.html">Logout</a></li>
        </ul>

        <ul class="nav navbar-nav hidden">
          <li><%= link_to "Profile", current_user %></li>
          <li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
          <li class="divider"></li>
          <li>
            <%= link_to "Log out", logout_path, method: "delete" %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body class="with-top-navbar">
    <% if logged_in? %>
    <%= render 'layouts/header' %>
    <% end %>
    <div class="container-fluid container-fill-height">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%#= render 'layouts/footer' %>
      <% #debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>